
PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

^^^^^^^

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



使用jupyter-notebook自动导入的是默认环境（即base环境，需要将pytorch安装到这个环境中）

In [9]:
import sys
sys.path

['',
 '/home/jinbo/anaconda3/lib/python35.zip',
 '/home/jinbo/anaconda3/lib/python3.5',
 '/home/jinbo/anaconda3/lib/python3.5/plat-linux',
 '/home/jinbo/anaconda3/lib/python3.5/lib-dynload',
 '/home/jinbo/anaconda3/lib/python3.5/site-packages',
 '/home/jinbo/anaconda3/lib/python3.5/site-packages/IPython/extensions',
 '/home/jinbo/.ipython']

In [10]:
from __future__ import print_function
import torch

In [11]:
# 创建一个 5x3 矩阵, 但是未初始化:

In [12]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00, -5.8591e+02],
        [ 4.5719e-41, -2.2072e+07,  4.5719e-41],
        [ 2.4726e-26,  3.0764e-41,  2.4726e-26],
        [ 3.0764e-41, -2.4561e+07,  4.5719e-41],
        [-2.3841e+07,  4.5719e-41,  1.9500e+18]])


创建一个随机初始化的矩阵:



In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0557, 0.5689, 0.4523],
        [0.3043, 0.7310, 0.9974],
        [0.1213, 0.7150, 0.4663],
        [0.8365, 0.7276, 0.8726],
        [0.2540, 0.5927, 0.0394]])


创建一个0填充的矩阵，数据类型为long:



In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [15]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [16]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3579,  0.1620,  0.1816],
        [-0.1349,  1.0141, -0.9383],
        [-0.4145,  0.9721, -0.3795],
        [-0.1299,  0.3077,  0.5782],
        [-0.2472,  0.0927,  0.1711]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [17]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

^^^^^^^^^^

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.0167,  0.5697,  0.8921],
        [ 0.4038,  1.8121, -0.1037],
        [ 0.0057,  1.8366,  0.4387],
        [ 0.0564,  1.0999,  0.8778],
        [ 0.6381,  0.8043,  0.6582]])


加法2


In [19]:
print(torch.add(x, y))

tensor([[ 2.0167,  0.5697,  0.8921],
        [ 0.4038,  1.8121, -0.1037],
        [ 0.0057,  1.8366,  0.4387],
        [ 0.0564,  1.0999,  0.8778],
        [ 0.6381,  0.8043,  0.6582]])


提供输出tensor作为参数



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

替换



In [ ]:
# adds x to y
y.add_(x)
print(y)

<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [ ]:
print(x[:, 1])

``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9233])
1.923306941986084


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

使用from_numpy自动转化



In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [27]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改

tensor([2.9233], device='cuda:0')
tensor([2.9233], dtype=torch.float64)
