#### numpy 数组操作

In [1]:
import numpy as np
A = np.array(range(12))

In [7]:
A = A.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
B = A.copy()
C = B.ravel(order = 'C') # ‘C’ 按行， ‘F’ 按列
D = B.ravel(order = 'F') # 展平一个数组
print(B)
print(C)
print(D)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [16]:
# numpy.transpose(arr,axes) 
# arr：要操作的数组
# axes：整数列表，对应维度，通常所有维度都会对换。
C = np.transpose(A) # 翻转数组
print(C)
print(A.T) # 转置

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [19]:
A = np.array(range(72)).reshape(3,4,6)
A

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

In [25]:
C = np.transpose(A)
print('C:\n',C)
print('\nA的转置:\n',A.T)

C:
 [[[ 0 24 48]
  [ 6 30 54]
  [12 36 60]
  [18 42 66]]

 [[ 1 25 49]
  [ 7 31 55]
  [13 37 61]
  [19 43 67]]

 [[ 2 26 50]
  [ 8 32 56]
  [14 38 62]
  [20 44 68]]

 [[ 3 27 51]
  [ 9 33 57]
  [15 39 63]
  [21 45 69]]

 [[ 4 28 52]
  [10 34 58]
  [16 40 64]
  [22 46 70]]

 [[ 5 29 53]
  [11 35 59]
  [17 41 65]
  [23 47 71]]]

A的转置:
 [[[ 0 24 48]
  [ 6 30 54]
  [12 36 60]
  [18 42 66]]

 [[ 1 25 49]
  [ 7 31 55]
  [13 37 61]
  [19 43 67]]

 [[ 2 26 50]
  [ 8 32 56]
  [14 38 62]
  [20 44 68]]

 [[ 3 27 51]
  [ 9 33 57]
  [15 39 63]
  [21 45 69]]

 [[ 4 28 52]
  [10 34 58]
  [16 40 64]
  [22 46 70]]

 [[ 5 29 53]
  [11 35 59]
  [17 41 65]
  [23 47 71]]]


In [39]:
# 连接数组
# numpy.concatenate((a1, a2, ...), axis)
# a1, a2, ...：相同类型的数组
# axis：沿着它连接数组的轴，默认为 0
A = np.array(range(12)).reshape(3,4)
B = np.array(range(20,32)).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
B

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
np.concatenate((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
np.concatenate((A,B),axis = 1) # 沿着轴 1 连接两个数组

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

In [43]:
# numpy.stack 函数用于沿新轴连接数组序列，格式如下:
# numpy.stack(arrays, axis)
np.stack((A,B),0) # 沿轴 0 堆叠两个数组

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [44]:
np.stack((A,B),1) # 沿轴 1 堆叠两个数组

array([[[ 0,  1,  2,  3],
        [20, 21, 22, 23]],

       [[ 4,  5,  6,  7],
        [24, 25, 26, 27]],

       [[ 8,  9, 10, 11],
        [28, 29, 30, 31]]])

In [45]:
# numpy.hstack 是 numpy.stack 函数的变体
# 它通过水平堆叠来生成数组。
np.hstack((A,B))
# np.hstack((A,B),1) 是错误的用法，没有 1 维度

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

In [48]:
# numpy.vstack 是 numpy.stack 函数的变体
# 它通过垂直堆叠来生成数组
np.vstack((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

##### 分割数组

In [53]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# numpy.split(ary, indices_or_sections, axis)
# indices_or_sections：如果是一个整数，就用该数平均切分，
# 如果是一个数组，为沿轴切分的位置（左开右闭)


np.split(A,3) # 将数组分为三个大小相等的子数组

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [68]:
C = np.array(range(10,22))
print(C)
print(np.split(C,[1,3,9])) # 将数组在一维数组中表明的位置分割
print(np.split(A,[0,2]))

[10 11 12 13 14 15 16 17 18 19 20 21]
[array([10]), array([11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21])]
[array([], shape=(0, 4), dtype=int64), array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [72]:
# numpy.hsplit 函数用于水平分割数组，
# 通过指定要返回的相同形状的数组数量来拆分原数组
np.hsplit(A,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [73]:
# numpy.vsplit 沿着垂直轴分割数组
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

#####  数组元素的添加与删除

In [74]:
A 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
print(A.shape) 
B = np.resize(A,(2,2,3)) # 返回指定形状的新数组
print(B)
print(A.shape)

(3, 4)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(3, 4)


In [91]:
# 添加数组
# 不表示添在哪一个维度，append 函数返回的始终是一个一维数组
B = np.append(A,[[99,98,97,96]]) 
C = np.append(A,[99,98,97,96]) 
print(B)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 99 98 97 96]
[ 0  1  2  3  4  5  6  7  8  9 10 11 99 98 97 96]


In [92]:
np.append(A,[[99,98,97,96]],axis = 0) # 注意两层中括号

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [99, 98, 97, 96]])

In [113]:
D = np.array([[99],
     [98],
     [97],
     [96]])
print(D)
print(D.shape,A.shape)
B = np.array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])
np.append(A,B,axis = 1)
# np.append(A,D,axis = 1) # 看来两个矩阵的列数也得一样，不然报错


[[99]
 [98]
 [97]
 [96]]
(4, 1) (3, 4)


array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

In [115]:
A = np.array(range(72)).reshape(3,4,6)
A

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

In [117]:
# 必须提供轴参数，不然数组会被展开成一维
np.insert(A,2,[666],axis=0) # 沿 0 轴在 2 位置 插入[666]，维度不足，广播

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47]],

       [[666, 666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666, 666]],

       [[ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]]])

In [118]:
np.insert(A,2,[666],axis=1) # 沿 1 轴在 2 位置 插入[666]

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [666, 666, 666, 666, 666, 666],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [666, 666, 666, 666, 666, 666],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [666, 666, 666, 666, 666, 666],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]]])

In [119]:
np.insert(A,2,[666],axis=2) # 沿 2 轴在 2 位置 插入[666]

array([[[  0,   1, 666,   2,   3,   4,   5],
        [  6,   7, 666,   8,   9,  10,  11],
        [ 12,  13, 666,  14,  15,  16,  17],
        [ 18,  19, 666,  20,  21,  22,  23]],

       [[ 24,  25, 666,  26,  27,  28,  29],
        [ 30,  31, 666,  32,  33,  34,  35],
        [ 36,  37, 666,  38,  39,  40,  41],
        [ 42,  43, 666,  44,  45,  46,  47]],

       [[ 48,  49, 666,  50,  51,  52,  53],
        [ 54,  55, 666,  56,  57,  58,  59],
        [ 60,  61, 666,  62,  63,  64,  65],
        [ 66,  67, 666,  68,  69,  70,  71]]])

In [132]:
I = np.array([[666,777,888,999,555,444],
    [999,888,777,666,555,444],
    [111,222,333,444,555,666]])
I2 = [111,222,333,444,555,666]
print(I.shape)
print(A.shape)
print('# 沿 1 轴在 2 位置 插入 I')
print(np.insert(A,2,I,axis=1)) # 沿 1 轴在 2 位置 插入 I
print('# 沿 1 轴在 2 位置 插入 I2')
print(np.insert(A,2,I2,axis=1)) # 沿 1 轴在 2 位置 插入 I2

(3, 6)
(3, 4, 6)
# 沿 1 轴在 2 位置 插入 I
[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [666 777 888 999 555 444]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29]
  [ 30  31  32  33  34  35]
  [999 888 777 666 555 444]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]
  [111 222 333 444 555 666]
  [ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]]]
# 沿 1 轴在 2 位置 插入 I2
[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [111 222 333 444 555 666]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29]
  [ 30  31  32  33  34  35]
  [111 222 333 444 555 666]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]
  [111 222 333 444 555 666]
  [ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]]]


In [133]:
A

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

In [139]:
np.delete(A,2,axis = 1) # 删除 1 轴 位置 2 的元素

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [66, 67, 68, 69, 70, 71]]])