##### http://www.runoob.com/numpy/numpy-tutorial.html

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape) # 维度
print(A.size) # 元素总个数
print(A.ndim) # 秩，即有多少个维度

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [3]:
l = range(24)
B = np.array(l)
B = B.reshape(4,3,2)
print(B)
print(B.ndim) # 秩为 3
print(B.size) 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3
24


创建数组

In [4]:
shape = (2,3)
np.zeros(shape, dtype = int) # 创建全零数组

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.empty(shape, dtype = float) # 创建随机值数组

array([[6.93135006e-310, 6.93135006e-310, 6.93135006e-310],
       [6.93135006e-310, 6.93135006e-310, 6.93135006e-310]])

In [6]:
np.ones(shape, dtype = float) # 创建全 1 数组

array([[1., 1., 1.],
       [1., 1., 1.]])